version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: benkimim-app
    container_name: benkimim-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - benkimim-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: benkimim-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - benkimim-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: benkimim-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: benkimim
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: benkimim_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - benkimim-network

  redis:
    image: redis:alpine
    container_name: benkimim-redis
    restart: unless-stopped
    networks:
      - benkimim-network

networks:
  benkimim-network:
    driver: bridge

volumes:
  dbdata: